import { Category, CategoryMongoDB } from "./entities";

export const CONNECTIONS = {
  mysql: {
    normal: {
      type: "mysql",
      host: "mysql",
      port: 3306,
      username: "root",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "mysql",
      host: "mysql_tmpfs",
      port: 3306,
      username: "root",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
  postgres: {
    normal: {
      type: "postgres",
      host: "postgres",
      port: 5432,
      username: "postgres",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "postgres",
      host: "postgres_tmpfs",
      port: 5432,
      username: "postgres",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
  mongo: {
    normal: {
      type: "mongodb",
      host: "mongo",
      port: 27017,
      username: "root",
      password: "root",
      database: "fullcycle",
      authSource: "admin",
      synchronize: true,
      logging: false,
      entities: [CategoryMongoDB],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "mongodb",
      host: "mongo_tmpfs",
      port: 27017,
      username: "root",
      password: "root",
      database: "fullcycle",
      authSource: "admin",
      synchronize: true,
      logging: false,
      entities: [CategoryMongoDB],
      subscribers: [],
      migrations: [],
    },
  },
};
